<?php
/** @var Mage_Core_Block_Template $this */
if(!Mage::helper("divvit_divvit")->isEnabled()) return;
?>
<script type="text/javascript">
//<![CDATA[
!function(){var t=window.divvit=window.divvit||[];t.DV_VERSION="magento-1.0.1",t.init=function(t){var e=document.createElement("script");e.setAttribute("type","text/javascript"),e.setAttribute("async",!0),e.setAttribute("src","https://tag.divvit.com/tag.js?id="+t);var r=document.getElementsByTagName("script")[0];r.parentNode.insertBefore(e,r)},t.functions=["customer","pageview","cartAdd","cartRemove","cartUpdated","orderPlaced","nlSubscribed","dv"];for(var e=0;e<t.functions.length;e++){var r=t.functions[e];t[r]=function(e){return function(){return Array.prototype.unshift.call(arguments,e),t.push(arguments),t}}(r)}}();

divvit.init('<?php echo Mage::helper("divvit_divvit")->getMerchantSiteId() ?>');
divvit.pageview();

<?php if(Mage::getSingleton("customer/session")->isLoggedIn()): ?>
divvit.customer({
    customerId: "<?php echo Mage::getSingleton("customer/session")->getCustomerId() ?>"
});
<?php endif; ?>

<?php if($this->helper("divvit_divvit")->hasCartData()): ?>
<?php echo $this->getChildHtml("divvit_cart") ?>
<?php Mage::helper("divvit_divvit")->resetCartData() ?>
<?php endif; ?>
//]]>
</script>
